// <auto-generated />
namespace CitelProject.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ProductTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003072104219_ProductTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
